# before: librarian-chef install

environments: &environments
  development: &development
    attributes: &attributes
      redmine:
        git_revision: '2.3.3'
        db:
          rails_env: development
      mysql:
        server_root_password: 'root'
        server_debian_password: 'root'
        server_repl_password: 'root'
    run_list: &run_list
      - apt::default
      - redmine::dependencies
      - redmine::default
      - redmine::database
      - redmine::nginx
    nodes:
      vagrant:
        host: 10.0.0.10
        user: vagrant
        password: vagrant
        vagrant: { IP: 10.0.0.10 } # gusteau chokes if you don't specify IP for vagrant VM

# Include overrides in .gusteau.local.yml; pay attention to indentation and yaml overriding.
# See http://atechie.net/2009/07/merging-hashes-in-yaml-conf-files/
<%= File.read(".gusteau.local.yml") if File.exists? '.gusteau.local.yml' %>
